# Generated by Django 3.0.6 on 2020-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdef_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('user', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('protocol', models.CharField(max_length=30)),
            ],
        ),
    ]
