# Generated by Django 3.0.6 on 2020-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdef_web', '0003_auto_20200530_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
