# Generated by Django 3.0.6 on 2020-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdef_web', '0006_blacklist_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
