# Generated by Django 3.0.6 on 2020-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdef_web', '0007_auto_20200816_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
